server:
  port: 8081
spring:
  application:
    name: productcenter
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9091/eureka/
  instance:
    instance-id: productcenter-8081
    prefer-ip-address: true