server:
  port: 8073
spring:
  application:
    name: usercenter
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9091/eureka/
  instance:
    instance-id: usercenter-8073
    prefer-ip-address: true