server:
  port: 8083
spring:
  application:
    name: productcenter
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9091/eureka/
  instance:
    instance-id: productcenter-8083
    prefer-ip-address: true